export default function SamplePDFPreview() {
  return (
    <section className="py-16 px-4 bg-surface">
      <div className="max-w-3xl mx-auto text-center">
        <h2 className="font-heading font-semibold text-2xl text-text-primary mb-3">
          What your clients will see
        </h2>
        <p className="text-text-secondary mb-8">
          A professional one-page demographic report, ready to attach to any client email.
        </p>
        {/* SVG mockup of a PDF report */}
        <div className="bg-white border border-border rounded-lg shadow-md p-8 max-w-md mx-auto animate-fade-in-up transition-shadow duration-normal hover:shadow-lg">
          <div className="border-b-2 border-primary pb-3 mb-6 text-left">
            <div className="font-heading font-bold text-xl text-primary">Austin, TX</div>
            <div className="text-sm text-text-secondary">Demographic Report — ZIP 78701</div>
          </div>
          <div className="grid grid-cols-2 gap-4 mb-6">
            {[
              { label: 'Population', value: '42,581' },
              { label: 'Median Income', value: '$78,200' },
              { label: 'Home Value', value: '$425,000' },
              { label: 'Employment', value: '94.2%' },
            ].map(item => (
              <div key={item.label} className="border border-border rounded-md p-3 text-left">
                <div className="text-xs text-text-secondary uppercase tracking-wide">{item.label}</div>
                <div className="font-heading font-bold text-lg text-text-primary">{item.value}</div>
              </div>
            ))}
          </div>
          {/* Simplified chart bars */}
          <div className="text-left mb-4">
            <div className="text-xs font-semibold text-text-primary mb-2">Age Distribution</div>
            {[
              { label: 'Under 18', w: '18%' },
              { label: '18–34', w: '32%' },
              { label: '35–54', w: '28%' },
              { label: '55+', w: '22%' },
            ].map(bar => (
              <div key={bar.label} className="flex items-center gap-2 mb-1">
                <span className="text-[10px] text-text-secondary w-14">{bar.label}</span>
                <div className="flex-1 bg-bg rounded h-2">
                  <div className="bg-primary rounded h-2" style={{ width: bar.w }} />
                </div>
              </div>
            ))}
          </div>
          <div className="border-t border-border pt-2 text-[10px] text-text-secondary/60 flex justify-between">
            <span>Source: U.S. Census Bureau, ACS 5-Year</span>
            <span>Generated by ZipScope</span>
          </div>
        </div>
      </div>
    </section>
  );
}
